# Grafana Datasource Provisioning for Release Quality Assessment

apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"

  # TimescaleDB (PostgreSQL) datasource
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: release_quality
    user: rq_user
    secureJsonData:
      password: rq_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: true

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'  # If Loki is added
      nodeGraph:
        enabled: true
